language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: beta-xcode6.2
r_packages:
- knitr
- covr
r_github_packages:
- eddelbuettel/drat
- cloudyr/aws.cloudwatch
- cloudyr/aws.cloudtrail
- cloudyr/aws.iam
- cloudyr/aws.s3
- cloudyr/aws.ec2
- cloudyr/aws.ses
- cloudyr/aws.glacier
after_failure:
  email:
    recipients:
    - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
#- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash knitreadme.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash drat.sh
env:
  global:
    secure: Gm6mV1VYsi0ecQwkN34KfK+jbqbsSjWGSHhK5GAOJfgrtnjrYWbC638UtLvwqEW/pumCAOc7wOg/1/T7o2/YTKcharnbjxzT7+PZ2EdfO8gznahH3y70tFmmoz+JbXVuwKyrl4Vwz+AAyax2uvLmvl7Y8fGProxrudXYmTxGq9ZiJIzWZZpo9FWSgzpeE+/DXibhwOyTK1oalHeLbwhnOs6rEMecnArBGN5URRnr9PpXxb5B+w9oaMeuNiq3WumpCK//kybenR0gSDMx+LP93a3OtVfxqxNRBRDe8LSdhMsrk9aNW3uPNe9CjPpGdnchTe8idysFiT6fdQW41GJhnmTcZykGQ2VjaiGqE0avgfboD4PAkym0WxPVfGbAR/UfueNifdZeK+ESW8uveQKNdkk/ZUoVU8lsfehvOukOPOCXQ8rWhFvv459q5PUPclIrXlQsSiZfFE51318EgtUEtJoy3431DeIsM+N+sLetTJ47+NQA/UNH/1CQgwjg3oUql9clWfdMgZUI+d1AWcE4Lq+FRGWy9JNO6CmorGrc3VsvvIBWWqDm3OIUoUi/G/YlxGDPwHPCzN4tz4MpWLkB5Ph8vAyC7Ln2iJEIml4dC8VX6QRA5sbyABJQT+Z8q2pTnRWIGsELxtwQUZlc46NNpyAAdZJxWCKfZU3Vf4oGH5E=
